import {default as Footer} from './Footer'
import {default as Layout} from './Layout'
import {default as Navbar} from './Navbar'
import {default as Producto} from './Producto'
import {default as HeroBanner} from './HeroBanner'
import {default as FooterBanner} from './FooterBanner'
import {default as carro} from './carro'